version: "{branch} {build}"

os: Visual Studio 2014 CTP4

environment:
  matrix:
    # 64 bit
    - PLATFORM: x64
      CONFIGURATION: Release
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - git clone https://github.com/GeorgeV220/VoteRewards.git  
  - cd VoteRewards
  
build_script:
  - gradle clean build javadoc jar shadowJar
  
artifacts:
  - path: VoteRewards\build\libs\
  
cache:
  - C:\Users\appveyor\.m2
on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/k3rn31p4nic/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/k3rn31p4nic/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL
