name: release version

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[c skip]')"

    steps:
      - uses: actions/checkout@v2

      - name: Build and Test
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "clean install package -Ddockerfile.skip -DdockerCompose.skip -Djib.skip"

      - name: Release
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-16-openjdk/
        with:
          git-release-bot-name: "GeorgeV22 bot"
          git-release-bot-email: "bot@georgev22.com"
          
          access-token: ${{ secrets.SECRET_ACCESS_KEY }}
          
          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Dmaven.deploy.skip=true"

          gpg-enabled: false
